sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - py.test --cov pagarme
after_success:
  - coveralls
